#!/usr/bin/python3

import sys

def factors(n):
    # return a list of factors of n
    result = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            result.append(i)
    return result

# read numbers from the file
with open(sys.argv[1], 'r') as f:
    for line in f:
        n = int(line)
        # try to factorize n
        for p in factors(n):
            q = n // p
            print(f'{n}={p}*{q}')
            break

